---
# tasks file for get-ami-of-autoscaling-group

- name: Get facts of ASG
  ec2_asg_facts:
    name: "{{asg_name}}"
  register: asg

- name: Get facts of LC
  ec2_lc_facts:
    name: "{{asg.results[0].instances[0].launch_configuration_name}}"
  register: lc

- name: Get facts of AMI
  ec2_ami_find:
    ami_id: "{{lc.launch_configurations[0].image_id}}"
    region: "{{region}}"
  register: ami

- set_fact:
    old_ami: {
      "ami_id"             : "{{ami.results[0].ami_id}}",
      "security_groups"    : "{{lc.launch_configurations[0].security_groups}}",
      "vpc_subnet_id"      : "{{asg.results[0].vpc_zone_identifier}}",
      "volumes"            : "{{ami.results[0].block_device_mapping}}",
      "availability_zones" : "{{asg.results[0].instances[0].availability_zone}}",
      "keypair"            : "{{lc.launch_configurations[0].key_name}}",
      "instance_type"      : "{{lc.launch_configurations[0].instance_type}}"}
